apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vllm-waiting
  namespace: vllm-lab
spec:
  scaleTargetRef:
    name: vllm
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
  triggers:
    - type: prometheus
      metricType: AverageValue
      metadata:
        serverAddress: http://prometheus.vllm-lab.svc.cluster.local:9090
        query: sum(vllm:num_requests_waiting{job="vllm",namespace="vllm-lab"})
        threshold: '3'
        activationThreshold: '3'
        ignoreNullValues: 'false'
